"""init

Revision ID: 7b753cbe7790
Revises: 622792f466ff
Create Date: 2025-11-26 23:02:25.793210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b753cbe7790'
down_revision: Union[str, Sequence[str], None] = '622792f466ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'categories', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'creator_id')
    # ### end Alembic commands ###
